### ISSUE TITLE
Attempted to call an undefined method named "setQueueName" of class "OldSound\RabbitMqBundle\RabbitMq\Consumer". 

### ISSUE THREAD

**Issue by zneel** [kaliop-uk/kueueingbundle#4]
Hi, I'm trying to use your bundle to set up a Notification System and I'm having an error:
`Attempted to call an undefined method named "setQueueName" of class "OldSound\RabbitMqBundle\RabbitMq\Consumer". `
Looks like the adapter doesn't work anymore?
Am I using the bundle wrong?
Thanks

```yml
old_sound_rabbit_mq:

    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'user'
            password: 'passw'
            vhost:    '/'
            lazy:     false

    consumers:
        console_command:
            connection: default
            exchange_options:
                name: kaliop_queueing.console_command.exchange
                type: topic
            queue_options:
                name: kaliop_queueing.console_command.default_queue
                routing_keys: [ '#' ]
            callback: myConsumerService
```
